### ISSUE TITLE
hi guys，

### ISSUE THREAD

**Issue by hanxi2719** [itskaizad/Elitedesk-800-G4-Hackintosh#1]

**Comment by hanxi2719** [comment]
may I know your Hardware Specifications，AMD Graphics? THNAKS!

**Comment by itskaizad** [comment]
i5 8500T, Intel Q370 chipset, BCM4350 BT+Wifi

**Comment by hanxi2719** [comment]
AMD graphic?



------------------ Original ------------------

**Comment by hanxi2719** [comment]
And wlan card is dw1820a?   Thanks for your confirm


发自我的iPhone

------------------ Original ------------------

**Comment by itskaizad** [comment]
No GPU, although if you have one it should run natively. Yes for DW1820A.

**Comment by hanxi2719** [comment]
OK，thanks again


------------------ Original ------------------
